# Generated by Django 5.1.4 on 2025-03-16 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('question_type', models.CharField(choices=[('logical', 'Logical Reasoning'), ('verbal', 'Verbal Reasoning'), ('numerical', 'Numerical Reasoning'), ('spatial', 'Spatial Reasoning')], max_length=50)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
            ],
        ),
        migrations.CreateModel(
            name='IQTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_score', models.IntegerField(default=0)),
                ('verbal_score', models.IntegerField(default=0)),
                ('numerical_score', models.IntegerField(default=0)),
                ('spatial_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iq_results', to='recommenderApp.prediction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_results', to='recommenderApp.studentprofile')),
            ],
        ),
    ]
