# Generated by Django 5.1.4 on 2025-03-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderApp', '0002_iqquestion_iqtestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='age',
        ),
    ]
